# Create test11 namespace (Dont need to create namespace, it will create in the pod spec, but goot to be explicit)
apiVersion: v1
kind: Namespace
metadata:
  name: test13
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
  namespace: test13
spec:
  schedule: "* * * * *"  # This means the job will run every min
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo "Hello, World!"
          restartPolicy: OnFailure