services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redisui:
    image: ghcr.io/joeferner/redis-commander
    ports:
      - "8081:8081"
    environment:
        REDIS_HOSTS: "redis"
        READ_ONLY: "true"
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.27
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200