# Create test3 namespace (Dont need to create namespace, it will create in the pod spec, but goot to be explicit)
apiVersion: v1
kind: Namespace
metadata:
  name: test10
---
# Create configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: test10
data:
  somedata: "somevalue"
  index.html: |
    <html>
    <head>
        <title>Welcome to nginx!</title>
    </head>
    <body>
        <h1>Hello World from index file in config map!</h1>
    </body>
    </html>
---
# Create nginx deployment in test4 namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test10
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # Update pods one by one, no downtime deployment
    # type: Recreate # Terminate all pods before creating new ones
    # Other deployment types like canary supported via ingress routing
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.5 # Image versions 1.25.1, 1.25.5, 1.26.2
        env:
        - name: SOME_DATA
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: somedata
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet: 
            path: /index.html
            port: 80
            httpHeaders:
            - name: User-Agent
              value: k8s-probe-liveness
        startupProbe:
          httpGet: 
            path: /index.html
            port: 80
            httpHeaders:
            - name: User-Agent
              value: k8s-probe-startup
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-configmap