# Create test3 namespace (Dont need to create namespace, it will create in the pod spec, but goot to be explicit)
apiVersion: v1
kind: Namespace
metadata:
  name: test7
---
# Create nginx deployment in test4 namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test7
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate # Update pods one by one, no downtime deployment
    # type: Recreate # Terminate all pods before creating new ones
    # Other deployment types like canary supported via ingress routing
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1 # Image versions 1.25.1, 1.25.5, 1.26.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet: 
            path: /index.html
            port: 80
            httpHeaders:
            - name: User-Agent
              value: k8s-probe-liveness
        startupProbe:
          httpGet: 
            path: /index.html
            port: 80
            httpHeaders:
            - name: User-Agent
              value: k8s-probe-startup
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test7
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer