apiVersion: v1
kind: Namespace
metadata:
  name: elk
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elk
spec:
  version: 8.17.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false