# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
# Create Issuer for Self-Signed Certificate for RabbitMQ (cert-manager)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-selfsigned-issuer
  namespace: rabbitmq
spec:
  selfSigned: {}
---
# Create Self-Signed Certificate for RabbitMQ (cert-manager)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: rabbitmq
spec:
  dnsNames:
    - apps.mehmood.us
  secretName: selfsigned-cert-tls
  issuerRef:
    name: rabbitmq-selfsigned-issuer
---
# Create RabbitMQ Cluster
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: message-broker
  namespace: rabbitmq
spec:
  replicas: 1
  tls:
    secretName: selfsigned-cert-tls  
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      management.path_prefix = /mqui
  persistence:
    storage: 1Gi
---
# Create the LetsEncrypt Issuer for RabbitMQ (cert-manager)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: rabbitmq
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: altaf.mehmood@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
---
# Create ingress route
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-broker-ingress
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ingress.class: "nginx"  # Make sure ingress-nginx controller is used
    cert-manager.io/issuer: "letsencrypt-prod"    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - apps.mehmood.us
      secretName: ingress-tls-cert-secret 
  rules:
  - host: apps.mehmood.us  
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: message-broker
            port: 
              number: 15671
---
