apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rabbitmq-selfsigned-issuer
  namespace: rabbitmq
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: rabbitmq
spec:
  dnsNames:
    - apps.mehmood.us
  secretName: selfsigned-cert-tls
  issuerRef:
    name: rabbitmq-selfsigned-issuer
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: message-broker
  namespace: rabbitmq
spec:
  replicas: 1
  tls:
    secretName: selfsigned-cert-tls  
  rabbitmq:
    additionalConfig: |
      log.console.level = info
  persistence:
    storage: 1Gi
---