# Create namespace kuard
apiVersion: v1
kind: Namespace
metadata:
  name: test121
---
# Create the self-signed issuer and certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: test121
spec:
  selfSigned: {}
---
# Create the self-signed certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: test121
spec:
  dnsNames:
    - apps.mehmood.us
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned-issuer
---