name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to ACR
      run: docker login ${{ACR_LOGINSERVER}} -u ${{ACR_USERNAME}} -p ${{ACR_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build Day2/sampleapi --file Day2/sampleapi/Dockerfile --tag ${{ACR_LOGINSERVER}}/sampleapi:$(date +%s)

    - name: Push Docker image
      run: docker push ${{ACR_LOGINSERVER}}/sampleapi:$(date +%s)
